name: Build
run-name: ${{ github.actor }} build BlingFire
on: [push]
jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            name: "Windows Latest MSVC",
            os: windows-latest,
            artifact: "Release/blingfiretokdll.dll",
            build_type: "Release",
            cc: "cl",
            ccx: "cl",
          }
        - {
            name: "Ubuntu latest GCC",
            os: ubuntu-latest,
            artifact: "libblingfiretokdll.so",
            build_type: "Release",
            cc: "gcc",
            cxx: "g++"
          }
        - {
            name: "MacOS latest Clang",
            os: macos-latest,
            artifact: "libblingfiretokdll.dylib",
            build_type: "Release",
            cc: "clang",
            cxx: "clang++"
          }
    steps:
      - uses: actions/checkout@v2
      - uses: seanmiddleditch/gha-setup-vsdevenv@master

      - name: Print env
        run: |
          echo github.event.action: ${{ github.event.action }}
          echo github.event_name: ${{ github.event_name }}
      - name: Install dependencies on Windows
        if: startsWith(matrix.config.os, 'windows')
        run: |
          choco install cmake
          cmake --version
      - name: Install dependencies on Ubuntu
        if: startsWith(matrix.config.os, 'ubuntu')
        run: |
          sudo apt-get update
          sudo apt-get install cmake
          cmake --version
          gcc --version
      - name: Build
        shell: bash
        run: |
          mkdir Release
          cd Release
          cmake -DCMAKE_BUILD_TYPE=Release ..
          cmake --build . --config Release
      - uses: actions/upload-artifact@v3
        with:
          name: sharedlib_${{ matrix.config.os }}
          path: Release/${{ matrix.config.artifact }}
